# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:7.10

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            # validate syntax
            - run: yarn lint

            # run tests!
            - run: yarn test

            # Create the deployment package
            - run: yarn package

            # Install the AWS CLI
            - run: sudo apt-get -y -qq install awscli
            - run: aws --version

            # Deploy to S3
            - run: aws s3 sync dist s3://sincsports/lambda/

            # Update Lambda Function Code
            # I don't understand why this isn't working as it works when I execute it locally.
            # - run: aws lambda update-function-code --function-name client-sincsports-divisions-lambda --s3-bucket sincsports --s3-key lambda/client-sincsports-divisions-lambda.zip --publish
